### ISSUE TITLE
Emotes have stopped working?

### ISSUE THREAD

**Issue by tollus** [HiDeoo/YaTA#39]
**Describe the bug**

Almost all of my emotes (twitch global, BTTV, my channel emotes) do not auto complete. They also do not display in chat either. It appears to be due to the API 'emoticon_images' returns a 500 error. 

Note, this is not due to the latest release, this was happening to me previously before the upgrade. I tested a separate twitch account and emotes work fine for that one.

I wonder if it has some sort of limit to the amount of subscriptions it can request at once or something strange like that?

**To Reproduce**

(for me)

1. Go to any twitch chat.
2. See error in the dev tools, and see no emote icon in the chat box.
3. Also, trying to autocomplete any emotes will not work.

**Expected behavior**

I would expect to be able to see emotes as well as use emotes myself.

**Screenshots**

![ZsLX8aocGq](https://user-images.githubusercontent.com/1820386/70935646-acdcbd80-200e-11ea-8f13-78811b7f4b53.png)

**Environment (please complete the following information)**

| Software         | Version               |
| ---------------- | --------------------- |
| YaTA             | 1.12.0           |
| Browser          | Chrome  |
| Operating System | Windows          |

**Comment by HiDeoo** [comment]
Damn, that is an interesting one, thanks for the report.

I'll have to investigate this one because as you suspected, this is not related to the latest release and so far I cannot repro at all.

**Comment by HiDeoo** [comment]
Well, I couldn't find any relevant informations on why this API would return a 500, altho the 500 clearly indicates an error on Twitch end, the documentation doesn't mention anything that could lead to that, kinda reminds me of when Ske couldn't use his bits badge for 2 months for no reason 😆 

I pushed a new version where I implemented a workaround that I think should work in this specific case altho as I can't really repro / test it, I can't be 100% sure it'll work.

Please re-open / comment if it's still not working in your case.

**Comment by tollus** [comment]
Thanks for the try. Looks the same to me. If you want, I can checkout a branch and run locally if you want to try something else.

**Comment by HiDeoo** [comment]
Hmmm, I'll have to investigate a bit more as I'm out of idea so far without rechecking the code.

**Comment by tollus** [comment]
So I had done a little bit of debugging myself. I was able to remove the last of the emote set numbers from the link and it made it work. However, any other one instead did not fix it. So it somehow seems specific to that one number. I didn't get a chance to dig into more, I wanted to see where that number came from, and what it represented. (whether it was a sub or something else)

I was curious if maybe it was truncated or something wrong with the number in general.

**Comment by HiDeoo** [comment]
Interesting, maybe you could try with [this API](https://twitchemotes.com/apidocs):

> https://api.twitchemotes.com/api/v4/sets?id=100,29712

**Comment by tollus** [comment]
Yeah, it's specifically the number `893207471` which doesn't show up in that api.

**Comment by HiDeoo** [comment]
Good lord, what is that thing and why is that even returned for you 😄 (not even gonna ask why Twitch fails lamentably when passed this id ^^)

Thanks for the investigation, I guess now my next step will be finding what this is somehow ^^

**Comment by tollus** [comment]
I confirmed that's the value that I'm receiving in the IRC `USERSTATE` response in the `"emote-sets"` value. Definitely no visible truncation in the message.

**Comment by HiDeoo** [comment]
Would you be able to check, if you can ofc, if when hitting this path, you also get the `893207471` set?

https://github.com/HiDeoo/YaTA/blob/13e4de10534e4f9e599b8f8559abf932abf37f7d/src/containers/Chat.tsx#L901

**Comment by tollus** [comment]
it doesn't seem to get there

**Comment by HiDeoo** [comment]
Ha, you're not even hitting this path, that means that the workaround I added 10 days ago so that you would get emotes but not the faulty ones doesn't work https://github.com/HiDeoo/YaTA/commit/7960bfdce004af9ecb9c3ae41d230ef117c1b321

I'll investigate a bit more and setup a proper way to test this, maybe this path is throwing and we're not even getting to the `else` bit I added.

If that's the case, that should be an easy fix and I'm hoping we can get at least all emotes back working for you while ignoring this set.

**Comment by HiDeoo** [comment]
(and thanks again for taking the time to test all this)

**Comment by tollus** [comment]
It looks like it's coming from the twitch-js lib. The line under the 'USERSTATE' case statement:
`this._updateEmoteset(message.tags['emote-sets']);`

I don't think it's anything you explicitly call.

**Comment by HiDeoo** [comment]
Yeah, and I assumed this function callback would be called with an `error` when hitting this 500 and patching it to call my code even in case of an error would be enough (https://github.com/HiDeoo/YaTA/commit/7960bfdce004af9ecb9c3ae41d230ef117c1b321#diff-d035ee5b0264e36112cf7c4bc5fc1a09) but I guess my assumption is wrong and it's escaping this path somehow. 

I guess I'll be able to confirm this with a proper way to mock this 500.

**Comment by tollus** [comment]
Do I have to do something to patch my own version? or is that automatic when I `yarn run start`?

**Comment by HiDeoo** [comment]
Ohhh, you bring an interesting point I didn't even thought of, if you're running a local version (and not the prod one, which is patched), you may need a `yarn` (which is `yarn install`)

**Comment by tollus** [comment]
gotcha, I had done that running locally. I had even deleted the `node_modules` folder just in case.

**Comment by HiDeoo** [comment]
I was finally able to reproduce the issue. I used [Charles Proxy](https://www.charlesproxy.com/) to modify my own requests to this specific API and modify the query string on the fly by appending the faulty set you reported (`893207471`). I used a proxy instead of modifying any code to be sure I would be in the exact same scenario as you are without any code change.

I pushed [a patch](https://github.com/HiDeoo/YaTA/commit/f1f14195092cc749212463f3c0918e98514dd5d2) for the library involved which should workaround the issue. With it, you still get the `500` of course (the query string in the screenshot is not modified, only the network request one is):

<img width="1118" alt="Screenshot 2019-12-28 at 18 31 36" src="https://user-images.githubusercontent.com/494699/71547629-aea96800-29a2-11ea-9a99-69d5164ba363.png">

When failing, you would now be hitting the code path you were not hitting before: 

https://github.com/HiDeoo/YaTA/blob/13e4de10534e4f9e599b8f8559abf932abf37f7d/src/containers/Chat.tsx#L901

And after that, you would be able to use emotes as expected (this is after hitting the 500):

<img width="181" alt="Screenshot 2019-12-28 at 18 32 11" src="https://user-images.githubusercontent.com/494699/71547641-cf71bd80-29a2-11ea-891f-672e5f5d5c3b.png">

Of course, all of this is based on the assumption that this second API I use to fetch emotes is not broken for you too 🤞 

Would you be able to fetch the latest changes from the repo and test locally? (I assume a basic `yarn` would be enough to apply the latest patch properly altho I've seen it fail on some OSes, in that case your solution to remove node_modules and re-running yarn would work too).

If you can't or don't want to, do not hesitate to tell me and I'll push that change as is in production in a few days.

**Comment by tollus** [comment]
Yeah, i'll give it a shot either today or tomorrow. Thanks so much for checking it out.

**Comment by tollus** [comment]
My apologies, I tried to add the change but I still saw the error. I'm not sure if I did it correctly though, but based on your explanation, it's probably resolved.

**Comment by HiDeoo** [comment]
Hmm, that would be a shame if the other API also fails to return proper data.

I'll keep the changes anw as it's still an improvement compared to the previous behavior.

I also found a similar case to your issue which was reported to Twitch altho, so far, no comment or anything https://discuss.dev.twitch.tv/t/retrieving-emotes-from-particular-emotesets-fail/23450

I'll close this issue for now as I think I'm at the maximum I can do on my end in this particular case.

Thanks for all your help.

**Comment by tollus** [comment]
The latest release did fix this. I still see the 500, but then it loads from the other api. Thanks!

**Comment by HiDeoo** [comment]
Wow, that is good news 🎉
